---
# deploys the product.yml stack

- name: Display all hosts
  debug:
    msg: "{{ inventory_hostname }}"

- name: create networks
  docker_network:
    name: "{{ lookup('env', 'CI_PROJECT_PATH_SLUG') }}_{{ item }}_{{ lookup('env', 'ENV') }}"
    driver: overlay
  with_items: "{{ docker_networks }}"

- name: Deploy product stack file
  copy: src=./stacks/{{ stack }}.yml dest=.

- name: Login to {{ docker_registry }} using {{ docker_registry_user }} {{ docker_registry_password }} 
  shell: echo "{{ docker_registry_password }}" | docker login -u "{{ docker_registry_user }}" --password-stdin "{{ docker_registry }}"

- name: Actually deploy the stack
  command: docker stack deploy -c {{ stack }}.yml {{ lookup('env', 'CI_PROJECT_PATH_SLUG') }}_{{ stack }}_{{ env }} --with-registry-auth
  environment: "{{ lookup('gitlab_env', 'COMMON', 'REVIEW', 'ENV')|combine(item) }}"
  register: result
  ignore_errors: yes
  with_items:
    - {'SWARM': "{{ lookup('env', 'SWARM') }}" }

- name: "debug: dump env variables"
  shell: env > /tmp/$LOGNAME.docker.stack.deploy.env
  environment: "{{ lookup('gitlab_env', 'COMMON', 'REVIEW', 'ENV')|combine(item) }}"
  with_items:
    - {'SWARM': "{{ lookup('env', 'SWARM') }}" }
  when: debug or result is failed

- name: remove remote stack file {{ stack }}.yml
  file:
    path: "{{ stack }}.yml"
    state: absent
  when: debug or result is succeeded

- name: check if deploy failed
  debug:
    msg: "successfully deployed"
  failed_when: result is failed

